server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/qma?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/